### ISSUE TITLE
Yazi no longer recognizes LibreOffice and Word files

### ISSUE THREAD

**Issue by bertradio** [sxyazi/yazi#1091]
UPDATE -- I tried an earlier version of yazi 0.2.5 (c65a14c 2024-04-23) and the problem is not there. So it's something that happened since.

#######################

### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Kitty 0.35

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```

Yazi
    Version: 0.2.5 (53d658d 2024-05-26)
    OS: linux-x86_64 (unix)
    Debug: false

Ya
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "Ya 0.2.5 (bf1c325 2024-05-20)\n", stderr: "" })

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect: Kitty

Adaptor
    Adaptor.matches: Kitty

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: Some("wayland-0")
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/bin/bash")
    EDITOR: None
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.44\nmagic file from /etc/magic:/usr/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })
    block: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/bert/.local/state/yazi" directory.


```

</details>

### Describe the bug

For some reason, yazi stopped recognizing LibreOffice and Word files. This behavior started after I updated to latest. Also I am running in a Debian 12 VM under Crostini and recently my Chromebook crashed. I restored everything, but not sure things are working properly. In nemo if I hit enter on an office or Word file it opens properly in LibreOffice. Same thing in Doublecmd. So Linux recognizes the files and what should open them. But not in yazi. Is this a yazi issue? Or a Linux issue?

### Expected Behavior

LibreOffice and Word files should open when I hit <cr>. Also I have set up previewers in plugins. They also don't work anymore. 

### To Reproduce

Run yazi with my yazi.toml

### Configuration

Using build 53d658d. 

Here is my yazi.toml...

# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio          = [ 2, 3, 6 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
linemode       = "none"
show_hidden    = false
show_symlink   = false
scrolloff      = 5

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener] # sets of definitions of openers referenced in rules below

edit = [
	{ run = 'nvim "$@"',  desc = "nvim",  block = true },
  { run = 'vim "$@"',   desc = "vim",   block = true },
  { run = 'gvim "$@"',  desc = "Gvim",  block = true },
	{ run = 'geany "$@"', desc = "Geany", block = true },
  { run = 'meld "$@"',  desc = "meld",  block = true },
]

open = [
	{ run = 'xdg-open "$@"',  desc = "Open" },
]

reveal = [
  { run = 'xdg-open "$(dirname "$0")"', desc = "Open dir in nemo" },
	{ run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF" },
]

extract = [
	{ run = 'file-roller "$1"', desc = "Archive Manager" },
	{ run = 'unar "$1"',        desc = "Extract to new folder" },
	{ run = 'peazip "$1"',      desc = "Peazip" },
]

play = [
	{ run = 'celluloid "$@"', desc = "Celluloid", orphan = false },
	{ run = 'audacity "$@"',  desc = "Audacity",  orphan = false },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info" },
]

mp4edit = [
{ run = 'audacity "$@"',  desc = 'Audacity',  orphan = false },
{ run = 'celluloid "$@"', desc = 'Celluloid', orphan = false },
]

aup3edit = [
	{ run = 'audacity "$@"',  desc = "Audacity", orphan = false },
]

pdfedit = [
	{ run = 'okular "$@"',      desc = "Okular",       orphan = false },
	{ run = 'evince "$@"',      desc = "Evince",       orphan = false },
	{ run = 'pdfarranger "$@"', desc = "PDF Arranger", orphan = false },
]

mdedit = [
	{ run = 'nvim "$@"',   desc  = "nvim",   block = true },
  { run = 'typora "$@"', desc  = "typora", block = true },
	{ run = 'geany "$@"',  desc  = "geany",  block = true },
	{ run = 'gvim "$@"',   desc  = "gvim",   block = true },
	{ run = 'vim "$@"',    desc  = "vim",    block  = true },
	{ run = 'meld "$@"',   desc  = "meld",   block = true },
]

[open] #rules for which opener(s) for which filetypes

rules = [ 

	{ name = "*/",       use =         [ "edit", "open", "reveal" ] },
  { name = "*.mp4",    use =         [ "mp4edit", "reveal" ] },
  { name = "*.m4a",    use =         [ "mp4edit", "reveal" ] },
  { name = "*.conf*",  use =         [ "edit", "reveal" ] },
  { name = "*.pdf",    use =         [ "pdfedit", "reveal" ] },
  { name = "*.md",     use =         [ "mdedit", "reveal" ] },
  { name = "*.aup3",   use =         [ "aup3edit", "reveal" ] },

	{ mime = "text/*",  use =          [ "edit", "reveal" ] },
	{ mime = "image/*", use =          [ "open", "reveal" ] },
	{ mime = "audio/*", use =          [ "play", "reveal" ] },
  { mime = "video/*", use =          [ "play", "reveal" ] },
	{ mime = "inode/x-empty", use =    [ "edit", "reveal" ] },

	{ mime = "*/javascript",     use = [ "edit", "reveal" ] },
	{ mime = "application/json", use = [ "edit", "reveal" ] },

	{ mime = "application/zip",             use = [ "extract" ] },
	{ mime = "application/gzip",            use = [ "extract" ] },
	{ mime = "application/x-tar",           use = [ "extract" ] },
	{ mime = "application/x-bzip",          use = [ "extract" ] },
	{ mime = "application/x-bzip2",         use = [ "extract" ] },
	{ mime = "application/x-7z-compressed", use = [ "extract" ] },
	{ mime = "application/x-rar",           use = [ "extract" ] },
	{ mime = "application/xz",              use = [ "extract" ] },

# Fallback
  { mime = "*", use = [ "open", "reveal" ] },

]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]
suppress_preload = false

[plugin]

# my custom previewers and pre-loaders

prepend_previewers = [
	{ name = "*txt",                        run = "code" },
  { name = "*.md",                        run = "glow" },
  { name = "*.od*",                       run = "odt" },
  { name = "*.wps",                       run = "odt" },
  { name = "*.xlsx",                      run = "xlsx" },
  { name = "*.xls",                       run = "xls" },
  { name = "*.docx",                      run = "docx" },
  { name = "*.doc",                       run = "doc" },
  { mime = "text/csv",                    run = "csv"},
  { mime = "audio/*",                     run = "exifaudio" },
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
]

# removed below when added to core
# preloaders = [
#
# 	{ name = "*", cond = "!mime", run = "mime", multi = true, prio = "high" },
# 	# Image
# 	{ mime = "image/vnd.djvu",    run = "noop" },
# 	{ mime = "image/*",           run = "image" },
# 	# Video
# 	{ mime = "video/*",           run = "video" },
# 	# PDF
# 	{ mime = "application/pdf",   run = "pdf" },
# ]

previewers = [ # standard previewers

  # directories
	{ name = "*/", run = "folder", sync = true },

	# Code
	{ mime = "text/*",                 run = "code" },
	{ mime = "*/xml",                  run = "code" },
	{ mime = "*/javascript",           run = "code" },
	{ mime = "*/x-wine-extension-ini", run = "code" },

	# JSON
	{ mime = "application/json",       run = "json" },

	# Image
	{ mime = "image/vnd.djvu",         run = "noop" },
	{ mime = "image/*",                run = "image" },

	# Video
	{ mime = "video/*",                run = "video" },

	# PDF
	{ mime = "application/pdf",        run = "pdf" },

	# Archive
	{ mime = "application/zip",             run = "archive" },
	{ mime = "application/gzip",            run = "archive" },
	{ mime = "application/x-tar",           run = "archive" },
	{ mime = "application/x-bzip",          run = "archive" },
	{ mime = "application/x-bzip2",         run = "archive" },
	{ mime = "application/x-7z-compressed", run = "archive" },
	{ mime = "application/x-rar",           run = "archive" },
	{ mime = "application/xz",              run = "archive" },

# Fallback
	{ name = "*", run = "file" },
	# { name = "*", run = "hexyl" }, # use hex viewer as fallback

]

# input labels and locations

[input]

# cd
cd_title  = "Change directory:"
cd_origin = "center"
cd_offset = [ 0, 2, 50, 3 ]

# create
create_title  = "Create:"
create_origin = "center"
create_offset = [ 0, 2, 50, 3 ]

# rename
rename_title  = "Rename:"
rename_origin = "center"
rename_offset = [ 0, 1, 50, 3 ]

# trash
trash_title 	= "Move {n} selected file{s} to trash? (y/N)"
trash_origin	= "center"
trash_offset	= [ 0, 2, 40, 3 ]

# delete
delete_title 	= "DELETE {n} SELECTED PERMANENTLY? (y/n)"
delete_origin	= "center"
# delete_offset	= [ 0, 2, 50, 3 ]
# put message higher than others to make it stand out
delete_offset	= [ 0, -5, 40, 3 ]

# filter
filter_title  = "Filter:"
filter_origin = "center"
filter_offset = [ 0, 2, 30, 3 ]

# find
find_title  = [ "Find next:", "Find previous:" ]
find_origin = "center"
find_offset = [ 0, 2, 50, 3 ]

# search
search_title  = "Search via {n}:"
search_origin = "center"
search_offset = [ 0, 2, 50, 3 ]

# shell
shell_title  = [ "Shell:", "Shell (block):" ]
shell_origin = "center"
shell_offset = [ 0, 2, 30, 3 ]

# overwrite
overwrite_title  = "Overwrite an existing file? (y/N)"
overwrite_origin = "center"
overwrite_offset = [ 0, 2, 50, 3 ]

# quit
quit_title  = "{n} task{s} running, sure to quit? (y/N)"
quit_origin = "center"
quit_offset = [ 0, 2, 50, 3 ]

[select]
open_title  = "Open with:"
open_origin = "center"
open_offset = [ 0, 1, 50, 11 ]

[which]
sort_by        = "none"
sort_sensitive = false
sort_reverse   = false

[log]
enabled = false

[headsup]

### Anything else?

Love yazi! Really need this fixed.

**Comment by sxyazi** [comment]
Hi, can you upload these files for me to test?

**Comment by bertradio** [comment]
Which files?

**Comment by sxyazi** [comment]
LibreOffice and Word files that dont work

**Comment by bertradio** [comment]
Attached are 2 test files I just made with LibreOffice. These do not work with the latest build but do work with Yazi 0.2.5 (c65a14c 2024-04-23). The same problem exists with any LO or MS Office file. As I said, the work fine with nemo and Doublecmd which open them properly.

**Comment by bertradio** [comment]
And here is a file I made with MS Office 365 on line. Does not work either.

**Comment by sxyazi** [comment]
I can't receive the attachment. It looks like GitHub dropped it. You'll need to drag and upload it using the GitHub web UI.

**Comment by bertradio** [comment]
[Attachments.zip](https://github.com/sxyazi/yazi/files/15456053/Attachments.zip)

**Comment by sxyazi** [comment]
Should be fixed in https://github.com/sxyazi/yazi/commit/e8c35cba9a7a2ec307f3992aef87aae21899d1b0, please try it. 

Thanks for reporting this bug!

**Comment by bertradio** [comment]
Now it properly opens the right programs. But it still does not trigger the previewer I have specified. Attached is a zip with my entire config.

[yaziconfig.zip](https://github.com/sxyazi/yazi/files/15456436/yaziconfig.zip)

**Comment by sxyazi** [comment]
Hi, I resubmitted the commit https://github.com/sxyazi/yazi/commit/b81b707a3ea767e04fb02fddfc3a093e7769229e, please try again.

**Comment by bertradio** [comment]
Perfect! That works as it did before.

Thanks again for all your hard work and responsiveness.

Bert
