### ISSUE TITLE
default theme is not friendly for light terminal background

### ISSUE THREAD

**Issue by tkkcc** [sxyazi/yazi#149]
yazi 0.1.4 on archlinux, no custom config
alacritty terminal with light background
open yazi and type `g`, the keymap prompt text is unrecognizable:
![image](https://github.com/sxyazi/yazi/assets/17373509/a8a9aa4d-f756-4646-bc63-8ba3be62551f)

**Comment by sxyazi** [comment]
Have you made a light theme for Yazi?

**Comment by tkkcc** [comment]
no yazi config, but I have custom $LS_COLORS, is it related?

```txt
rs=0:di=01;34:ln=01;36:mh=00:pi=01;33:so=01;35:do=01;35:bd=01;33;01:cd=01;33;01:or=01;31;01:mi=00:su=01;41:sg=01;43:ca=01;41:tw=01;42:ow=0:st=01;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:

```

**Comment by sxyazi** [comment]
This is related to the theme system, and I am currently in the middle of refactoring the theme system.

I will address this once I have finished it.

**Comment by asim215** [comment]
I have following with gruvbox light alacritty and after tweaking config.
![20230914_18h41m04s_grim](https://github.com/sxyazi/yazi/assets/7127165/26a4bf7c-0ca5-495e-a608-a9a2d6a07ee0)

**Comment by sxyazi** [comment]
Done by https://github.com/sxyazi/yazi/pull/221

**Comment by magnetophon** [comment]
Thanks for your work on this, @Eric-Song-Nop and @sxyazi!
When renaming, I still get unreadable text:

![image](https://github.com/sxyazi/yazi/assets/7645711/cfbcf2dd-b146-410c-803a-8bcac1d9796a)

**Comment by Eric-Song-Nop** [comment]
> Thanks for your work on this, @Eric-Song-Nop and @sxyazi! When renaming, I still get unreadable text:
> 

@magnetophon Can you provide me with the your theme file?

**Comment by sxyazi** [comment]
Hi @magnetophon, I made a new PR to fix it, https://github.com/sxyazi/yazi/pull/264, please give it a try.

**Comment by magnetophon** [comment]
> @magnetophon Can you provide me with the your theme file? 

I was testing without any config for yazi.

> Hi @magnetophon, I made a new PR to fix it, #264, please give it a try.

Compiling as we speak.

**Comment by magnetophon** [comment]
Yes, all fixed for me now.
Thanks!

**Comment by magnetophon** [comment]
There are still two cases where I get unreadable text.
1) When I ``interactive-cd``:
![image](https://github.com/sxyazi/yazi/assets/7645711/ea9ab0ba-37c4-428a-abd9-ae93f10a39a5)

2) In the help screen:
![image](https://github.com/sxyazi/yazi/assets/7645711/74df9bd6-d828-47b9-8c6b-bcd97fa3537d)

This is with the default theme.

**Comment by sxyazi** [comment]
Hi @magnetophon, what terminal theme are you using? My iTerm2 with Tango Light looks like:

<img width="857" alt="CleanShot 2023-11-07 at 19 22 12" src="https://github.com/sxyazi/yazi/assets/17523360/8347c528-cdf7-4217-b363-e7590aef0859">

By using the default theme config:

```toml
[completion]
border   = { fg = "blue" }
active   = { bg = "darkgray" }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""
```

**Comment by magnetophon** [comment]
I'm using wezterm.
When I try with alacritty, it's all readable.

I guess that means it's a bug in wezterm, or maybe a bug in the theme I'm using for wezterm?
