### ISSUE TITLE
Allow unordered TOML in configs

### ISSUE THREAD

**Issue by fufexan** [sxyazi/yazi#458]
### Is your feature request related to a problem? Please describe

Currently there is at least one place in the configs that requires ordered entries. That is, in the `[icons]` section inside `theme.toml`. It expects `"*"` and `"*/"` icons to be set after all other entries in order to match the others properly, otherwise it simply shows the default icons for files/directories instead of the proper matches.

This is an issue that's come up after trying to change the icons in my Home Manager config, which sorts the entries lexicographically. While the issue would be way harder to solve in Home Manager itself, it doesn't sound too hard to fix in yazi's code.

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Yazi should not expect ordered entries and instead treat `"*"` and `"*/"` as special entries.

### Describe alternatives you've considered

I could manually write the toml file instead of relying on Home Manager to generate it from Nix code, but this would be a temporary solution.

**Comment by sxyazi** [comment]
I plan to convert icons into a list and support icon colors (https://github.com/sxyazi/yazi/issues/402), in the upcoming breaking change version v0.2.0.

**Comment by sxyazi** [comment]
Done by https://github.com/sxyazi/yazi/pull/503

**Comment by fufexan** [comment]
@sxyazi I've just updated today and it seems the issue is not resolved. My `theme.toml` file is generated like this:

```toml
[[icon.rules]]
name = "*"
text = ""

[[icon.rules]]
name = "*/"
text = "󰉋"

[[icon.rules]]
name = ".config/"
text = ""

[[icon.rules]]
name = ".ssh/"
text = "󰢬"

[[icon.rules]]
name = "Desktop/"
text = ""

[[icon.rules]]
name = "Development/"
text = ""

[[icon.rules]]
name = "Documents/"
text = ""

[[icon.rules]]
name = "Downloads/"
text = "󰉍"

[[icon.rules]]
name = "Library/"
text = ""
# ...
```

And the `*` and `*/` icons still take precedence over all others. This does not happen when they're moved under all other rules.

**Comment by sxyazi** [comment]
Well, this deviates a bit from my purpose of adding `rules`. I added it with the intention that Nix users can more conveniently generate the structure as:

```toml
[icon]
rules = [
  { name = ".config/", text = "" },
  { name = ".ssh/", text = "" },
  { name = "*", text = "" },
  { name = "*/", text = "󰉋" }
]
```

instead of the previous:

```toml
[[icons]]
".config/" = ""
[[icons]]
".ssh/" = ""
[[icons]]
"*" = ""
[[icons]]
"*/" = "󰉋"
```

The latter is more difficult to ensure the order during generation.

I want to know if `rules` is still challenging for Nix (sorry, I've completely forgotten my Nix knowledge). If it is, I can provide alternative solutions.

As for changing the behavior of `"*"` and `"*/"`, that is not an acceptable solution because all other rules (openers, custom previewers, custom preloaders) are based on the order. Changing the matching behavior for one would mean encountering it elsewhere, and to completely solve it, all matching rules would need to be re-designed at the same time.

**Comment by fufexan** [comment]
Oh, managing the rules in nix is fine, that's just the TOML generated after converting the nix code, which looks like this
```nix
  programs.yazi.theme.icon.rules = [
    # Default
    { name = "*"; text = ""; }
    { name = "*/"; text = "󰉋"; }

    # Home
    { name = ".config/"; text = ""; }
    { name = ".ssh/"; text = "󰢬"; }
    { name = "Desktop/"; text = ""; }
    { name = "Development/"; text = ""; }
    { name = "Documents/"; text = ""; }
    { name = "Downloads/"; text = "󰉍"; }
    { name = "Library/"; text = ""; }
    { name = "Movies/"; text = ""; }
    { name = "Music/"; text = "󱍙"; }
    { name = "Pictures/"; text = "󰉏"; }
    { name = "Videos/"; text = ""; }
    { name = "Public/"; text = ""; }

    # ...
```

> As for changing the behavior of `"*"` and `"*/"`, that is not an acceptable solution because all other rules (openers, custom previewers, custom preloaders) are based on the order. Changing the matching behavior for one would mean encountering it elsewhere, and to completely solve it, all matching rules would need to be re-designed at the same time.

I see, so this has to be solved in Home Manager then. Worst case I can just link a toml file directly with `home.file`. Thanks for the explanation.

**Comment by sxyazi** [comment]
Hmm why do you place "Default" at the top rather than at the bottom? If this will work:

```nix
  programs.yazi.theme.icon.rules = [
    # Home
    { name = ".config/"; text = ""; }
    { name = ".ssh/"; text = "󰢬"; }
    { name = "Desktop/"; text = ""; }
    { name = "Development/"; text = ""; }
    { name = "Documents/"; text = ""; }
    { name = "Downloads/"; text = "󰉍"; }
    { name = "Library/"; text = ""; }
    { name = "Movies/"; text = ""; }
    { name = "Music/"; text = "󱍙"; }
    { name = "Pictures/"; text = "󰉏"; }
    { name = "Videos/"; text = ""; }
    { name = "Public/"; text = ""; }

    # ...

    # Default
    { name = "*"; text = ""; }
    { name = "*/"; text = "󰉋"; }
```
